import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "@/components/Provider/Provider";

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });


export const metadata = {
  title: "Finflow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
